source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target ‘YYSwiftLibrarys’ do
pod 'MBProgressHUD'
end

target ‘YYSwiftLibrarysUITests’ do
    pod 'MBProgressHUD'
end

target ‘YYSwiftLibrarysTests’ do
    pod 'MBProgressHUD'
end
